//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_INGRESO_STOCK
    {
        public DETALLE_INGRESO_STOCK()
        {
            this.DETALLE_SALIDA_STOCK = new HashSet<DETALLE_SALIDA_STOCK>();
        }
    
        public decimal ID_DETALLE_INGRESO { get; set; }
        public decimal STOCK_INICIAL { get; set; }
        public decimal STOCK_ACTUAL { get; set; }
        public System.DateTime FECHA_PRODUCCION { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public string LOTE { get; set; }
        public decimal INGRESO_STOCK_ID_INGRESO { get; set; }
        public decimal PRODUCTO_ID_PRODUCTO { get; set; }
    
        public virtual ICollection<DETALLE_SALIDA_STOCK> DETALLE_SALIDA_STOCK { get; set; }
        public virtual INGRESO_STOCK INGRESO_STOCK { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
