//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CesfamEntities : DbContext
    {
        public CesfamEntities()
            : base("name=CesfamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<DETALLE_INGRESO_STOCK> DETALLE_INGRESO_STOCK { get; set; }
        public DbSet<DETALLE_RECETA> DETALLE_RECETA { get; set; }
        public DbSet<DETALLE_SALIDA_STOCK> DETALLE_SALIDA_STOCK { get; set; }
        public DbSet<FABRICANTE> FABRICANTE { get; set; }
        public DbSet<INGRESO_STOCK> INGRESO_STOCK { get; set; }
        public DbSet<PACIENTE> PACIENTE { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<RECETA> RECETA { get; set; }
        public DbSet<REL_PACIENTE> REL_PACIENTE { get; set; }
        public DbSet<REL_RECETA> REL_RECETA { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<SALIDA_STOCK> SALIDA_STOCK { get; set; }
        public DbSet<TIPO_RECETA> TIPO_RECETA { get; set; }
        public DbSet<TIPO_SALIDA> TIPO_SALIDA { get; set; }
        public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public DbSet<TUTOR> TUTOR { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<REL_RESERVA> REL_RESERVA { get; set; }
    }
}
