//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        public PACIENTE()
        {
            this.RECETA = new HashSet<RECETA>();
            this.REL_PACIENTE = new HashSet<REL_PACIENTE>();
        }
    
        public decimal ID_PACIENTE { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string CORREO { get; set; }
        public string CODIGO_LIBRETA { get; set; }
        public string RUT { get; set; }
        public string DIRECCION { get; set; }
    
        public virtual ICollection<RECETA> RECETA { get; set; }
        public virtual ICollection<REL_PACIENTE> REL_PACIENTE { get; set; }
    }
}
