//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public RECETA()
        {
            this.DETALLE_RECETA = new HashSet<DETALLE_RECETA>();
            this.REL_RECETA = new HashSet<REL_RECETA>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal ID_RECETA { get; set; }
        public string ESTADO_RECETA { get; set; }
        public System.DateTime FECHA_RECETA { get; set; }
        public decimal TIPO_RECETA_ID_TIPO_RECETA { get; set; }
        public decimal PACIENTE_ID_PACIENTE { get; set; }
        public string DIAGNOSTICO { get; set; }
        public decimal CANTIDAD_TIEMPO { get; set; }
        public System.DateTime FECHA_ENTREGA { get; set; }
        public decimal USUARIO_ID_USUARIO { get; set; }
        public Nullable<decimal> CORREOENVIADO { get; set; }
    
        public virtual ICollection<DETALLE_RECETA> DETALLE_RECETA { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual TIPO_RECETA TIPO_RECETA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<REL_RECETA> REL_RECETA { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
