//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_RECETA
    {
        public decimal SALIDA_STOCK_ID_SALIDA_STOCK { get; set; }
        public decimal RECETA_ID_RECETA { get; set; }
        public decimal ID_REL_RECETA { get; set; }
        public decimal ID_RETIRA { get; set; }
    
        public virtual RECETA RECETA { get; set; }
        public virtual SALIDA_STOCK SALIDA_STOCK { get; set; }
    }
}
