//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.REL_RESERVA = new HashSet<REL_RESERVA>();
        }
    
        public decimal ID_RESERVA { get; set; }
        public string ESTADO_RESERVA { get; set; }
        public decimal RECETA_ID_RECETA { get; set; }
        public decimal PRODUCTO_ID_PRODUCTO { get; set; }
        public decimal CANTIDAD_RESERVA { get; set; }
        public decimal USUARIO_ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_RESERVA { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual RECETA RECETA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<REL_RESERVA> REL_RESERVA { get; set; }
    }
}
