//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALIDA_STOCK
    {
        public SALIDA_STOCK()
        {
            this.DETALLE_SALIDA_STOCK = new HashSet<DETALLE_SALIDA_STOCK>();
            this.REL_RECETA = new HashSet<REL_RECETA>();
            this.REL_RESERVA = new HashSet<REL_RESERVA>();
        }
    
        public decimal ID_SALIDA_STOCK { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal USUARIO_ID_USUARIO { get; set; }
        public decimal TIPO_SALIDA_ID_TIPO_SALIDA { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<DETALLE_SALIDA_STOCK> DETALLE_SALIDA_STOCK { get; set; }
        public virtual ICollection<REL_RECETA> REL_RECETA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual TIPO_SALIDA TIPO_SALIDA { get; set; }
        public virtual ICollection<REL_RESERVA> REL_RESERVA { get; set; }
    }
}
