//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SALIDA
    {
        public TIPO_SALIDA()
        {
            this.SALIDA_STOCK = new HashSet<SALIDA_STOCK>();
        }
    
        public decimal ID_TIPO_SALIDA { get; set; }
        public string NOMBRE_TIPO_SALIDA { get; set; }
    
        public virtual ICollection<SALIDA_STOCK> SALIDA_STOCK { get; set; }
    }
}
