//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_RECETA
    {
        public TIPO_RECETA()
        {
            this.RECETA = new HashSet<RECETA>();
        }
    
        public decimal ID_TIPO_RECETA { get; set; }
        public string NOMBRE_TIPO { get; set; }
    
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
