//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUTOR
    {
        public TUTOR()
        {
            this.REL_PACIENTE = new HashSet<REL_PACIENTE>();
        }
    
        public decimal ID_TUTOR { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string CORREO { get; set; }
        public string PARENTESCO { get; set; }
    
        public virtual ICollection<REL_PACIENTE> REL_PACIENTE { get; set; }
    }
}
