//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesfamDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.INGRESO_STOCK = new HashSet<INGRESO_STOCK>();
            this.RECETA = new HashSet<RECETA>();
            this.RESERVA = new HashSet<RESERVA>();
            this.SALIDA_STOCK = new HashSet<SALIDA_STOCK>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string USUARIO1 { get; set; }
        public string CLAVE { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public decimal TIPO_USUARIO_ID_TIPO_USUARIO { get; set; }
    
        public virtual ICollection<INGRESO_STOCK> INGRESO_STOCK { get; set; }
        public virtual ICollection<RECETA> RECETA { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        public virtual ICollection<SALIDA_STOCK> SALIDA_STOCK { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
